mongo:
  image: mongo

redis:
   image: redis

server1:
  build: server
  expose:
   - 2000
  links:
   - redis
   - mongo

server2:
  build: server
  expose:
   - 2000
  links:
   - redis
   - mongo

server3:
  build: server
  expose:
   - 2000
  links:
   - redis
   - mongo

proxy:
  build: haproxy
  links:
   - server1
   - server2
   - server3
   - client
  ports:
   - "80:80"
   - "70:70"

client:
  build: client
  expose:
   - 80
