mongo:
  image: mongo

redis:
   image: redis

server:
  build: server
  expose:
   - 2000
  links:
   - redis
   - mongo

proxy:
  build: haproxy
  links:
   - server
   - client
  ports:
   - "443:443"

client:
  build: client
  expose:
   - 80
