version: "2"

services:

    mongo:
        image: mongo

    redis:
        image: redis

    backend:
        image: monolithe/specsdirector-server
        environment:
            - GARUDA_MONGO_HOST=mongo
            - GARUDA_REDIS_HOST=redis
            - NO_AUTHENTICATION=1
        links:
            - redis
            - mongo
        depends_on:
            - redis
            - mongo
        ports:
            - 1984:1984

    frontend:
        image: monolithe/specsdirector-client
        depends_on:
            - backend
        # environment:
        #     - API_AUTO_ENDPOINT=https://192.168.99.100:1984
        ports:
            - 443:443
