# run first export DEFAULT_SSL_CERT="$(cat default-haproxy.pem)"

mongo:
  image: mongo

redis:
   image: redis

proxy:
  image: tutum/haproxy
  environment:
   - DEFAULT_SSL_CERT
   - TIMEOUT=connect 600000, client 600000, server 600000
  links:
   - server
   - client
  ports:
   - "443:443"
   - "80:80"

server:
  build: server
  environment:
   - NO_AUTHENTICATION=1
   - VIRTUAL_HOST=https://*:443/api/*
   - VIRTUAL_HOST_WEIGHT=1
   - HTTP_CHECK=OPTIONS /api/v1_0/events
  links:
   - redis
   - mongo

client:
  build: client
  environment:
  - VIRTUAL_HOST=https://*:443/, https://*:443/*
  - VIRTUAL_HOST_WEIGHT=0
  - EXCLUDE_PORTS=443
