# run first export DEFAULT_SSL_CERT="$(cat default-haproxy.pem)"

mongo:
  image: mongo

redis:
   image: redis

proxy:
  image: tutum/haproxy
  environment:
   - DEFAULT_SSL_CERT=-----BEGIN CERTIFICATE-----\nMIICLzCCAZgCCQC+DmpzOV2VXjANBgkqhkiG9w0BAQUFADBcMQswCQYDVQQGEwJV\nUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoT\nC0dhcnVkYSBDb3JwMRIwEAYDVQQDEwkxMjcuMC4wLjEwHhcNMTUxMDIxMTkyMzIz\nWhcNMTYxMDIwMTkyMzIzWjBcMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAU\nBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC0dhcnVkYSBDb3JwMRIwEAYD\nVQQDEwkxMjcuMC4wLjEwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAMGYikMQ\nX97FL0fs1knRc6T2y9FnMqZ3kn5MmnFjmYlQs+jqGgBaJBaFJmKZxWsW/knVmHy8\nqdTLofnV2IfjdESmP/h7sJS851OL7RlgYpvb7IB4OqO/db6J2eAhtVa6ZkmwbAlU\np8FNagLyb5UuTnZYFbRwuubGI2HKdYo66ejrAgMBAAEwDQYJKoZIhvcNAQEFBQAD\ngYEAb7F1qlkDvhpivsObNyNt9edMp8wxQzMtKJoklREOeyPp6nRbIN4pTomox4wF\nfw4Kx/Il+YTL8ddn1PxP5XIXwJq9QOZW//OYCfARFylc0Zu+cgnZ2vjD5ZqIYYFg\nQBaUlmblYfdC5+80nhZEB4Rvd17rgwibWCg4S1d0WaFwuuA=\n-----END CERTIFICATE-----\n-----BEGIN RSA PRIVATE KEY-----\nMIICWwIBAAKBgQDBmIpDEF/exS9H7NZJ0XOk9svRZzKmd5J+TJpxY5mJULPo6hoA\nWiQWhSZimcVrFv5J1Zh8vKnUy6H51diH43REpj/4e7CUvOdTi+0ZYGKb2+yAeDqj\nv3W+idngIbVWumZJsGwJVKfBTWoC8m+VLk52WBW0cLrmxiNhynWKOuno6wIDAQAB\nAoGAbWXvq5oTMuWmpDRXm3s6qFu2LWztmFg1dh1/oNexqYDrSZEQhGZrwjYXzNws\nTSm/JKYI92P9bHxt2apYI+IKjsxveAO7p2MN2DYFyRE/58FBhL4VSryyS8t7RIwF\nBFtl0Cd+R5+8T0MlgIVAGf0rOIFJP5jyjgmNYdjdi5aPguECQQDtLt6TBB06Olds\n/pJcFIKaXiqBkjDLwvUu7YOSIO/V31aE+Nu+7lcTTKDyXaD25Cd6lMauiSlH2Pud\nkTngozNZAkEA0PRsvaNq3pAYa/qvnTROzn6TPT+3zRr0nZSrJdkcOGOkwiQQHAy7\nbP/zj1Xv+ilcHrt42hVEd6UN/zfCXidJ4wJACYhatbnymsaBgQXyR/UjEqU6PB7u\nCyJ4zDwLj7H3MbdaONnvqwrVQRdRWKxerc2ZsJmOKrGkkRitdDXEB71HcQJAJ02C\nUp01Uc2auly5wYEAPbjzKvccNFkYn7dCBelzdGvRpq6v1QbUDimKf3BzpgM3j5RF\npAeSDEsgedvcFGehbwJAV+G83L+0FBiWiJp1RKt8hx+0tzPV0S5SgFK05Sebo/QW\nfJT1zy4fHhs9ca37CaveKplnWlxNx7+3WzrnKulrBg==\n-----END RSA PRIVATE KEY-----\n
   - TIMEOUT=connect 600000, client 600000, server 600000
  links:
   - server
   - client
  ports:
   - "443:443"
   - "80:80"

server:
  build: server
  environment:
   - NO_AUTHENTICATION=1
   - VIRTUAL_HOST=https://*:443/api/*
   - VIRTUAL_HOST_WEIGHT=1
   - HTTP_CHECK=OPTIONS /api/v1_0/events
  links:
   - redis
   - mongo

client:
  build: client
  environment:
  - VIRTUAL_HOST=https://*:443/, https://*:443/*
  - VIRTUAL_HOST_WEIGHT=0
  - EXCLUDE_PORTS=443
